name: Push 기반 CI/CD 테스트

# 트리거 지정, CI/CD가 작동하게 되는 원인, 이벤트등 정의
# main 브런치에서 push 이벤트(리슨->on)가 발생되면 아래 설정한 내용되고 작동한다!
on:
  push:
    branches:
      - main

# 개별 작업(jobs)을 순서대로 나열 (파이프라인)
jobs:
  # ci라는 잡을 하나 정의
  ci:
    # 어떤 os에서 잡을 진행할 것인가? -> github에서 클라우드방식으로 제공(내부적)
    runs-on: ubuntu-latest

    # 작업단계 지정
    steps:
      # 1. github에 저장되어 있는 최신 내용을 체크아웃 (소스를 모두 내려 받음)
      - name: 코드 Checkout
        uses: actions/checkout@v3

      # 환경변수 파일 생성(생략) => .env

  # 확인 or 단위테스트(생략)
      - name: 확인 검증
   # 여러개 명령어 작동시 -> |를 통해서 배치
        run: |
          pwd
          ls -al
          cat main.py
        shell: bash

  
  # CI쪽 서버에서 EC2 서버(배포용 서버)로 배포 -> SSH
      # 사전 -> AWS에서 EC2 하나 생성 -> ip/domain , ubuntu(사용자명) , key는 pem파일
      #     -> Github상 해당 저장소에 secrets 변수로 위의 3개 값을 세팅
      # EC2 서버의 ssh 인바운드 접근 제약 정보에서 특정 IP가 아닌 어느곳에서든 접근 가능하게 구성
      # 0.0.0.0
      # 보안..? 별로
      - name: sourcecode copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22 
        # 복사할 대상 (편의상 .(현재디렉토리))
          source: .  
        # ubuntu os가 세팅된 ec2 서버의 /home/ubuntu/projects/*.* 복사
          target: "/home/ubuntu/projects" 

          


