name: Push 기반 CI/CD 테스트

# 트리거 지정, CI/CD가 작동하게 되는 원인, 이벤트등 정의
# main 브랜치에서 push 이벤트(리슨->on)가 발생되면 아래 설정한 내용되고 작동한다!!
on:
  push:
    branches:
      - main

# 개별 작업(jobs)을 순서대로 나열 (파이프라인)
jobs:
  # ci라는 잡을 하나 설정
  ci:
    # 어떤 OS에서 잡을 진행할 것인가? -> github에서 클라우드방식으로 제공(내부적)
    runs-on:  ubuntu-latest

    # 작업 단계 지정
    steps:
      # 1. github에 저장되어 있는 최신 내용을 체크아웃 (소스를 모두 내려 받음)
      - name: 코드 checkout
        uses: actions/checkout@v3

      # 환경변수 파일 생성(생략) => .env

      # 확인 or 단위테스트(생략)
      - name: 확인 검증
        # 여러개 명령어 작동시 -> |를 통해서 배치
        run:  |
          pwd
          ls -al
          cat main.py
        shell:  bash
      
      # 여기서 부터는 CD 작업임 -------------------------------------------
      # CI쪽 서버에서 EC2 서버(배포용 서버)로 배포 -> SSH
      # 사전 -> AWS에서 EC2 하나 생성 -> ip/domain , ubuntu(사용자명) , key는 pem파일
      #     -> Github상 해당 저장소에 secrets 변수로 위의 3개 값을 세팅
      # EC2 서버의 SSH 인바운드의 접근 제약 정보에서 특정 IP가 아닌 어느곳에서던 접근 가능하게 구성
      # 0.0.0.0/0
      # 보안?..
      - name: sourcecode copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          # 복사할 대상 (편의상 .(현재디렉토리))
          source: .
          # ubuntu os가 세팅된 ec2 서버의 /home/ubuntu/projects/*.* 복사
          target: "/home/ubuntu/projects"
      
      # 시크릿변수에는 환경변수 (.env <- git 업로드 x)에 들어가는 내용들을 담을수도 있음
      # 개별 사항을 세팅 or yml에서 설정 or 동적으로 .env 만들어서 배포 등등 가능

      # 남은 사항 => 서비스 재가동 명령 전달!!
      # EC2 서버에 배포후 작동에 관련된 스크립트 작동
      - name: Run Script And Service Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # 1. 프로젝트 폴더 위치로 이동
            # cd /home/ubuntu/projects
            # 2. 가상환경에 추가된 패키지가 있다면
            # ./web/bin/pip install -r requirements.txt

            # 3. 서비스 재가동
            #    stop -> start 수동으로 진행시 확인 되었음
            #    restart 확인 필요 (리뷰때 확인)
            # sudo systemctl restart hello.service
            sudo systemctl stop hello.service
            sudo systemctl start hello.service